### ISSUE TITLE
mostrar errores con alertify

### ISSUE THREAD

**Issue by jlurgo** [jlurgo/rrhh#10]

**Comment by josetabuyo** [comment]
en todos los onError poner alertify
simular error en mock

promesa.error;

**Comment by josetabuyo** [comment]
@jlurgo  
![image](https://user-images.githubusercontent.com/3936281/91664167-c3a34180-eac3-11ea-85a5-9d24b4e438cb.png)
Para probarlo en cualquier lugar que mandes un dato string con el texto #ERROR#, el mock lo ataja y te manda un error. podés probar todos los servicios así, incluso los de consulta, los arreglé en el mock
