### ISSUE TITLE
mejorar vista de las lupitas

### ISSUE THREAD

**Issue by jlurgo** [jlurgo/rrhh#19]
![image](https://user-images.githubusercontent.com/3925806/90837246-e39a6e80-e327-11ea-934c-94986c61659c.png)

**Comment by josetabuyo** [comment]
Que no se solapen el número y el ícono
Mejorar el ícono

**Comment by josetabuyo** [comment]
![image](https://user-images.githubusercontent.com/3936281/91660530-e4ac6800-eaac-11ea-939a-7e354fb74e54.png)

**Comment by josetabuyo** [comment]
de Whapp;
- por ultimo..... aca (/Imagenes/detalle.png) tienen la lupa que usamos en REPORTES (para que sea el mismo icono)

**Comment by josetabuyo** [comment]
Usar icono bajar.png compartido en Whapp
