### ISSUE TITLE
Bloquear edicion de asistencia cuando un grupo/periodo esta incluido en un informe

### ISSUE THREAD

**Issue by jlurgo** [jlurgo/rrhh#24]
Ocultar botón de edición si tiene el informe generado
Desestimar comentarios para  el alcance inicial

**Comment by josetabuyo** [comment]
Si tiene informe mostrar solo un ojito en icono y mostrar el detalle de la entidad en solo lectura

**Comment by josetabuyo** [comment]
![image](https://user-images.githubusercontent.com/3936281/91660980-8cc33080-eaaf-11ea-9656-72330f5f56e3.png)

**Comment by josetabuyo** [comment]
![image](https://user-images.githubusercontent.com/3936281/91661018-ce53db80-eaaf-11ea-982e-0d9383d6e54e.png)
No mostrar posibilidad de editar la observación
Sacar "OK", poner "Cancel" con texto "Cerrar"

**Comment by josetabuyo** [comment]
Poner título: "Modo de Sólo Lectura porque el grupo ya está informado" en detalle
